version: '3.7'

volumes:
    logs:
        driver: local

services:
    php:
        image: php:8-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8090 -t src/public
        environment:
            docker: "true"
        ports:
            - 8090:8090
        volumes:
            - .:/var/www
            - logs:/var/www/logs

    composer:
        image: composer:2.4.3
        command: diagnose
        environment:
            docker: "true"
        volumes:
            - .:/app